import { Location } from "./components/Location";

export const locations: Location[] = [
  {
    title: "Location 1",
    location: {
      latitude: 50.08804,
      longitude: 19.99503,
    },
    description: "Location 1 is a charming property situated at a prime latitude of 50.08804 and longitude of 19.99503, offering a perfect blend of convenience and tranquility. This delightful home boasts three spacious rooms, ideal for families or individuals seeking ample living space. Priced at an attractive $150,000, the property provides excellent value for money in a desirable area. The surrounding neighborhood is known for its serene ambiance and easy access to local amenities, making it a highly sought-after location for prospective homeowners.",
    price: 150000,
    rooms: 3,
    area: 100,
    pricePerArea: 150000 / 100,
    imgURL: "https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg",
    phoneNumber: 1234567890,
  },
  {
    title: "Location 2",
    location: {
      latitude: 52.2,
      longitude: 21,
    },
    description: "Location 2 is an inviting property positioned at a strategic latitude of 52.2 and longitude of 21, promising both accessibility and comfort. This appealing home features four generously sized rooms, making it an excellent choice for larger families or those desiring extra space. With a competitive price tag of $100,000, this property offers remarkable affordability in a vibrant and convenient area. The locale is celebrated for its dynamic community and proximity to essential services, rendering it an ideal setting for those looking to enjoy a harmonious blend of urban and suburban living.",
    price: 100000,
    rooms: 4,
    area: 100,
    pricePerArea: 100000 / 100,
    imgURL: "https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg",
    phoneNumber: 1234567890,
  },
  {
    title: "Location 3",
    location: {
      latitude: 48.8566,
      longitude: 2.3522,
    },
    description: "Location 3 is an exquisite property nestled in the heart of a culturally rich and vibrant area, precisely at latitude 48.8566 and longitude 2.3522. This elegant home features four spacious rooms, providing ample living space for families or individuals seeking comfort and style. Priced at $120,000, it offers exceptional value in a highly coveted neighborhood. The property's prime location ensures easy access to local attractions, dining, and shopping, making it an ideal choice for those who appreciate convenience and sophistication.",
    price: 120000,
    rooms: 4,
    area: 100,
    pricePerArea: 120000 / 100,
    imgURL: "https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg",
    phoneNumber: 1234567890,
  },
  {
    title: "Location 4",
    location: {
      latitude: 40.7128,
      longitude: -74.0060,
    },
    description: "Location 4 is a cozy and affordable property situated at a prime latitude of 40.7128 and longitude of -74.0060. This charming home features two comfortable rooms, making it an ideal choice for singles, couples, or small families. Priced at an appealing $90,000, this property presents a fantastic opportunity to own a residence in a dynamic and sought-after area. The neighborhood is known for its vibrant atmosphere, rich cultural heritage, and convenient access to a wide range of amenities, ensuring a perfect blend of urban living and comfort.",
    price: 90000,
    rooms: 2,
    area: 100,
    pricePerArea: 90000 / 100,
    imgURL: "https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg",
    phoneNumber: 1234567890,
  },
  {
    title: "Location 5",
    location: {
      latitude: 34.0522,
      longitude: -118.2437,
    },
    description: "Location 5 is a splendid property located at latitude 34.0522 and longitude -118.2437, offering an ideal mix of luxury and convenience. This attractive home features four spacious rooms, perfect for families or individuals who need extra space. With a price of $114,000, it provides excellent value in a prestigious and lively neighborhood. The area is renowned for its vibrant culture, diverse dining options, and numerous entertainment venues, ensuring residents enjoy a dynamic and fulfilling lifestyle. This property is an exceptional opportunity to own a home in one of the most desirable locations.",
    price: 114000,
    rooms: 4,
    area: 100,
    pricePerArea: 114000 / 100,
    imgURL: "https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg",
    phoneNumber: 1234567890,
  },
  {
    title: "Location 6",
    location: {
      latitude: 35.6895,
      longitude: 139.6917,
    },
    description: "Location 6 is a remarkable property positioned at latitude 35.6895 and longitude 139.6917, offering an exceptional living experience in a vibrant and bustling area. This elegant home boasts four spacious rooms, making it an ideal choice for families or those seeking ample living space. Priced at $117,600, it presents a fantastic value in a highly sought-after neighborhood. The location is renowned for its rich cultural heritage, modern amenities, and excellent connectivity, providing residents with the perfect blend of tradition and contemporary living. This property is a unique opportunity to own a piece of prime real estate in an exciting and dynamic environment.",
    price: 117600,
    rooms: 4,
    area: 100,
    pricePerArea: 117600 / 100,
    imgURL: "https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg",
    phoneNumber: 1234567890,
  },
  {
    title: "Location 7",
    location: {
      latitude: -33.8688,
      longitude: 151.2093,
    },
    description: "Location 7 is an impressive property situated at latitude -33.8688 and longitude 151.2093, offering a luxurious and spacious living experience. This magnificent home features six expansive rooms, ideal for large families or those who desire extra space for comfort and versatility. Priced at $220,050, this property represents outstanding value in a prestigious and highly desirable neighborhood. The area is celebrated for its stunning views, vibrant cultural scene, and convenient access to a wealth of amenities, ensuring residents enjoy an upscale and dynamic lifestyle. This property is a rare opportunity to own a substantial and elegant home in an iconic and sought-after location.",
    price: 220050,
    rooms: 6,
    area: 100,
    pricePerArea: 220050 / 100,
    imgURL: "https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg",
    phoneNumber: 1234567890,
  },
];
